### PR TITLE
Add random_device emulation (cryptographically insecure)

### PR DESCRIPTION
**Pull request by kubkon**
Currently, Emscripten doesn't provide out-of-the-box solution for emulating `/dev/(u)random` for our use-case. This poses a problem for any WASM binaries relying on seedable prngs. I've taken a stub at emulating the entropy source according to the Emscripten guidelines [here](https://github.com/emscripten-core/emscripten/blob/4f1bcf1c7b1de20ecff13ae8ddfd1a727516d495/src/library_fs.js#L1332). While (obviously) cryptographically insecure, it does the job at emulating the entropy source while, at the same time, preserving the determinism.

NB after we agree on a solution here, I will backport it to [golemfactory/wasm](https://github.com/golemfactory/wasm).

related: golemfactory/golem-wasm-pack-template#1

### CODE REVIEW

**Comment by mbenke** [comment]
How about adding a test of this functionality? I.e. that ytou can get arandom number, not necessarily what it would be, even though the PR decription claims determinism.

**Comment by kubkon** [comment]
> How about adding a test of this functionality? I.e. that you can get arandom number, not necessarily what it would be, even though the PR decription claims determinism.

Thanks for the suggestions! As far as the determinism is concerned, neglecting the issue with floats, since the fix is based on `Math.random()`, and in Emscripten it is implemented simply as

```js
var MAGIC = 0;
Math.random = function() {
  MAGIC = Math.pow(MAGIC + 1.8912, 3) % 1;
  return MAGIC;
};
```

(see [here](https://github.com/emscripten-core/emscripten/blob/d9529aefcc54e4fddd0802e3da8e5fe5af2b2a54/src/deterministic.js#L7)), therefore, at every execution of the binary, it will *always* return the same value.

As far as testing is concerned, while I do in principle agree that a test would be nice to have, in this case, since we are simply providing a hook into Emscripten-implemented lib functions, I don't think it would bring anything of value to the table. Let me know what you think.

**Comment by kubkon** [comment]
> It seems it is not deterministic after all; subsequent runs give different results.

Yep, you're right. It turns out `Math.random` is provided by the SpiderMonkey engine, and is truly a PRNG, hence, defo not a viable solution for us if we want to keep determinism.

**Comment by kubkon** [comment]
> > It seems it is not deterministic after all; subsequent runs give different results.
> 
> Yep, you're right. It turns out `Math.random` is provided by the SpiderMonkey engine, and is truly a PRNG, hence, defo not a viable solution for us if we want to keep determinism.

@mbenke re-implemented as follows:

```js
var golem_MAGIC = 0;
golem_randEmu = function() {
  golem_MAGIC = Math.pow(golem_MAGIC + 1.8912, 3) % 1;
  return golem_MAGIC;
};
var crypto = {
  getRandomValues: function(array) {
    for (var i = 0; i < array.length; i++)
      array[i] = (golem_randEmu() * 256) | 0
  }
};
```

**Comment by mbenke** [comment]
Well done! Seems to work fine now

**Pull request merged**
